apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicator-kubernetes-replicator
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kubernetes-replicator
    app.kubernetes.io/instance: replicator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-replicator
      app.kubernetes.io/instance: replicator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubernetes-replicator
        app.kubernetes.io/instance: replicator
    spec:
      serviceAccountName: replicator-kubernetes-replicator
      securityContext: {}
      containers:
      - name: kubernetes-replicator
        securityContext: {}
        image: 271747276495.dkr.ecr.ap-northeast-1.amazonaws.com/kubernetes-replicator:latest
        imagePullPolicy: Always
        args: []
        ports:
        - name: health
          containerPort: 9102
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
        readinessProbe:
          httpGet:
            path: /healthz
            port: health
        resources: {}
      imagePullSecrets:
        - name: ecr-cred-helper
